const clientes = [
  {
    id: 1,
    nome: "Supermercado Bom Preço",
    regiao: "Norte",
    nivel: "Ouro",
    email: "contato@bompreco.com",
    telefone: "(xx) xxxx-xxxx",
  },
  {
    id: 2,
    nome: "Distribuidora Mega Bebidas",
    regiao: "Sul",
    nivel: "Prata",
    email: "contato@megabebidas.com",
    telefone: "(xx) xxxx-xxxx",
  },
  {
    id: 3,
    nome: "Restaurante Sabor Caseiro",
    regiao: "Nordeste",
    nivel: "Bronze",
    email: "contato@saborcaseiro.com",
    telefone: "(xx) xxxx-xxxx",
  },
  {
    id: 4,
    nome: "Lanchonete Top Lanches",
    regiao: "Sudeste",
    nivel: "Prata",
    email: "contato@toplanches.com",
    telefone: "(xx) xxxx-xxxx",
  },
  {
    id: 5,
    nome: "Hotel Estrela do Norte",
    regiao: "Norte",
    nivel: "Ouro",
    email: "contato@estreladonorte.com",
    telefone: "(xx) xxxx-xxxx",
  },
  {
    id: 6,
    nome: "Padaria Delícia",
    regiao: "Sul",
    nivel: "Prata",
    email: "contato@padariadelicia.com",
    telefone: "(xx) xxxx-xxxx",
  },
  {
    id: 7,
    nome: "Farmácia Popular",
    regiao: "Centro",
    nivel: "Bronze",
    email: "contato@farmaciapopular.com",
    telefone: "(xx) xxxx-xxxx",
  },
  {
    id: 8,
    nome: "Loja de Conveniência Rápida",
    regiao: "Oeste",
    nivel: "Bronze",
    email: "contato@convenienciarapida.com",
    telefone: "(xx) xxxx-xxxx",
  },
  {
    id: 9,
    nome: "Mercado Econômico",
    regiao: "Leste",
    nivel: "Prata",
    email: "contato@mercadoeconomico.com",
    telefone: "(xx) xxxx-xxxx",
  },
  {
    id: 10,
    nome: "Mercearia Familiar",
    regiao: "Sul",
    nivel: "Bronze",
    email: "contato@merceariafamiliar.com",
    telefone: "(xx) xxxx-xxxx",
  },
  {
    id: 11,
    nome: "Supermercado Top",
    regiao: "Centro",
    nivel: "Ouro",
    email: "contato@supermercadotop.com",
    telefone: "(xx) xxxx-xxxx",
  },
  {
    id: 12,
    nome: "Quitanda Saudável",
    regiao: "Leste",
    nivel: "Ouro",
    email: "contato@quitandazsaudavel.com",
    telefone: "(xx) xxxx-xxxx",
  },
  {
    id: 13,
    nome: "Loja de Orgânicos Natureza",
    regiao: "Oeste",
    nivel: "Prata",
    email: "contato@orgaonatureza.com",
    telefone: "(xx) xxxx-xxxx",
  },
  {
    id: 14,
    nome: "Minimercado Veloz",
    regiao: "Norte",
    nivel: "Bronze",
    email: "contato@minimercadoveloz.com",
    telefone: "(xx) xxxx-xxxx",
  },
  {
    id: 15,
    nome: "Empório da Economia",
    regiao: "Centro",
    nivel: "Ouro",
    email: "contato@emporiodaeconomia.com",
    telefone: "(xx) xxxx-xxxx",
  },
];

const produtos = [
  { id: 1, nome: 'Coca-Cola', quantidadeAtual: 60, quantidadeMaxima: 120, categoria: 'Refrigerantes' },
  { id: 2, nome: 'Fanta Laranja', quantidadeAtual: 96, quantidadeMaxima: 180, categoria: 'Refrigerantes' },
  { id: 3, nome: 'Fanta Uva', quantidadeAtual: 36, quantidadeMaxima: 96, categoria: 'Refrigerantes' },
  { id: 4, nome: 'Sprite', quantidadeAtual: 84, quantidadeMaxima: 144, categoria: 'Refrigerantes' },
  { id: 5, nome: 'Schweppes', quantidadeAtual: 48, quantidadeMaxima: 120, categoria: 'Refrigerantes' },
  { id: 6, nome: 'Água Mineral Crystal', quantidadeAtual: 144, quantidadeMaxima: 240, categoria: 'Águas' },
  { id: 7, nome: 'Água Mineral Bonafont', quantidadeAtual: 96, quantidadeMaxima: 180, categoria: 'Águas' },
];

export {clientes, produtos}